-- MySQL Script generated by MySQL Workbench
-- 12/16/15 14:34:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `st_addr` VARCHAR(100) NOT NULL,
  `addr_comp` VARCHAR(100) NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(2) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `lst_name` VARCHAR(45) NOT NULL,
  `fst_name` VARCHAR(45) NOT NULL,
  `cell_phone` VARCHAR(45) NULL,
  `home_phone` VARCHAR(45) NULL,
  `work_phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`member` (
  `fk_id_member` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`fk_id_member`),
  CONSTRAINT `fk_member_user`
    FOREIGN KEY (`fk_id_member`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`manager`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`manager` ;

CREATE TABLE IF NOT EXISTS `mydb`.`manager` (
  `fk_id_manager` INT NOT NULL,
  PRIMARY KEY (`fk_id_manager`),
  INDEX `fk_manager_user1_idx` (`fk_id_manager` ASC),
  CONSTRAINT `fk_manager_user1`
    FOREIGN KEY (`fk_id_manager`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`operator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`operator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`operator` (
  `fk_id_operator` INT NOT NULL,
  PRIMARY KEY (`fk_id_operator`),
  INDEX `fk_operator_user1_idx` (`fk_id_operator` ASC),
  CONSTRAINT `fk_operator_user1`
    FOREIGN KEY (`fk_id_operator`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`provider` ;

CREATE TABLE IF NOT EXISTS `mydb`.`provider` (
  `fk_id_provider` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fk_id_provider`),
  INDEX `fk_provider_user1_idx` (`fk_id_provider` ASC),
  CONSTRAINT `fk_provider_user1`
    FOREIGN KEY (`fk_id_provider`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service` (
  `id_service` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `fee` DOUBLE NOT NULL,
  PRIMARY KEY (`id_service`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`service_provided`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`service_provided` ;

CREATE TABLE IF NOT EXISTS `mydb`.`service_provided` (
  `fk_id_provider` INT NOT NULL,
  `fk_id_service` INT NOT NULL,
  `fk_id_member` INT NOT NULL,
  `current_date` DATETIME NOT NULL,
  `occurrence_date` DATE NOT NULL,
  `comment` VARCHAR(200) NULL,
  INDEX `fk_provider_has_service_service1_idx` (`fk_id_service` ASC),
  INDEX `fk_provider_has_service_provider1_idx` (`fk_id_provider` ASC),
  INDEX `fk_service_provided_member1_idx` (`fk_id_member` ASC),
  CONSTRAINT `fk_provider_has_service_provider1`
    FOREIGN KEY (`fk_id_provider`)
    REFERENCES `mydb`.`provider` (`fk_id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provider_has_service_service1`
    FOREIGN KEY (`fk_id_service`)
    REFERENCES `mydb`.`service` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_provided_member1`
    FOREIGN KEY (`fk_id_member`)
    REFERENCES `mydb`.`member` (`fk_id_member`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`login` ;

CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `fk_id_user` INT NOT NULL,
  `password` CHAR(32) NOT NULL,
  PRIMARY KEY (`fk_id_user`),
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`fk_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
